name: Deploy to Cloud Run

env:
  PROJECT_ID: bradjolicoeur-web
  ARTIFACT_REGISTRY_REGION: us-central1
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/bradjolicoeur-web/blast-cms/blast-cms

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        working-directory: ./src
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} .
          docker push ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Test Service
        run: |
          gcloud run deploy blast-cms-test \
            --image ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [build-and-publish, deploy-test]

    steps:
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Production Service
        run: |
          gcloud run deploy blast-cms \
            --image ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated
